// Action types
export const ACTIONS = {
  // Auth actions
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  
  // UI actions
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  SET_THEME: 'SET_THEME',
  SET_LANGUAGE: 'SET_LANGUAGE',
  
  // Data actions
  SET_FEED: 'SET_FEED',
  ADD_FEED_ITEM: 'ADD_FEED_ITEM',
  UPDATE_FEED_ITEM: 'UPDATE_FEED_ITEM',
  SET_ARTIST: 'SET_ARTIST',
  SET_SONG: 'SET_SONG',
  SET_USER_DATA: 'SET_USER_DATA',
  
  // Real-time actions
  SET_ONLINE_USERS: 'SET_ONLINE_USERS',
  ADD_MESSAGE: 'ADD_MESSAGE',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
  
  // Notification actions
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  MARK_NOTIFICATION_READ: 'MARK_NOTIFICATION_READ',
  SET_UNREAD_COUNT: 'SET_UNREAD_COUNT'
} 